Fix boolean argument in Nair Lauritzen divergent
firedrakeproject/gusto_case_studies pull request #28
Opened 2024-09-05 14:16 UTC by ta440

Set the boolean argparse option of --background_flow to default to False. This means that both false and true (--background_flow=True) configurations can be run, whereas previously it became True irrespective of command line input.

2024-09-05 15:57 UTC, tommbendall requested changes
Thanks Tim for spotting that this wasn't working.

Two main things:
- can you apply the same change to the non-divergent test?
- can you update the calls in the `test_transport.py` file?

2024-09-05 15:57 UTC, tommbendall commented on case_studies/transport/nair_lauritzen_divergent.py
> +    print(no_background_flow)
Can you remove this?

2024-09-06 11:03 UTC, ta440 commented on case_studies/transport/nair_lauritzen_divergent.py
> +    print(no_background_flow)
Oops, I have a habit of doing this!

2024-09-09 08:15 UTC, tommbendall approved these changes
Thanks Tim!

2024-09-09 08:15 UTC, merged